ProjectSite:
  is_a: Site
  slots:
    - estimatedEnergyUsage
    - actualEnergyUsage
    - estimatedFuelRequirement
    - actualFuelUsage
    - refuellingSchedule
    - fuelDeliveries
  description: A location within a project where hydrogen will be used to power NRMM
